### PR TITLE
Fixed logo in footer to match the logo in the header

### LINKED ISSUE #108: Logo in footer needs to match logo in header
Current logo in footer: Screenshot 2020-03-19 at 12 25 55 PM

Correct logo in header: 
Screenshot 2020-03-19 at 12 26 35 PM

### PR DESCRIPTION
**Pull request by mateusmarquezini**
## Hey, I just made a Pull Request!

Fixes #108 

- Fixed logo in footer to match the logo in the header;

backstage_footer_logo

#### :heavy_check_mark: Checklist

- [x] Website is working locally `yarn start`
- [x] Screenshots attached (for UI changes)
- [x] Prettier run on changed files

### CODE REVIEW

**Comment by stefanalund** [comment]
@katz95 I like it. What do you think?

**Comment by katz95** [comment]
@mateusmarquezini thank you so much for doing this! it's looking pretty good! if you could leave the default state of the logo at 100% opacity and take out the hover interaction, that would be great! An example of what I mean is seen here in the Spotify logo in the footer of this website (https://www.spotify.com/). thank you thank you thank you!

**Comment by mateusmarquezini** [comment]
> @mateusmarquezini thank you so much for doing this! it's looking pretty good! if you could leave the default state of the logo at 100% opacity and take out the hover interaction, that would be great! An example of what I mean is seen here in the Spotify logo in the footer of this website (https://www.spotify.com/). thank you thank you thank you!

Hi @katz95 ! Sure, no problem! It's a pleasure!

What do you think? I kept 100% logo opacity and removed the hover interaction.

backstage_footer_logo_updated

**Comment by katz95** [comment]
Thank you @mateusmarquezini !! 🙏

**Pull request merged**
