### PR TITLE
Update Favicon to new logo

### LINKED ISSUE #160: Update Favicon to new logo
Hi! We have a new logo that we'd love to update the site favicon with. The favicon should look like the following image. I've attached a ZIP file with all the favicon assets. Let me know if those work for you all. 
Backstage Identity_Assets_Artwork_RGB_04 Icon_Teal

[favicon_package_v0.16.zip](https://github.com/spotify/backstage-microsite/files/4557612/favicon_package_v0.16.zip)

Attached is a screenshot of some of the instructions from the favicon generator site. They may or may not be relevant haha.
Screenshot 2020-04-30 at 12 14 29 PM

### PR DESCRIPTION
**Pull request by kazuma0129**
## Hey, I just made a Pull Request!

fixed #160 

Before
スクリーンショット 2020-05-01 22 31 49

After
スクリーンショット 2020-05-01 22 31 40

#### :heavy_check_mark: Checklist

- [x] Website is working locally `yarn start`
- [x] Screenshots attached (for UI changes)
- [x] Prettier run on changed files

### CODE REVIEW

**Comment by stefanalund** [comment]
How does this look on a non-black browser tab?

**Comment by kazuma0129** [comment]
@stefanalund 
Thanks for your comment.
Newly, I took a screenshot of the case where the tab is white and the case where it is gray.
The color of the tab changes when the tab is in focus in the browser and when it is not.
I also took a picture of them and attached it below.

White - Focused
スクリーンショット 2020-05-03 21 08 12
White - Non focusing
スクリーンショット 2020-05-03 21 10 36

Gray - Focused
スクリーンショット 2020-05-03 21 09 58
Gray - Non focusing
スクリーンショット 2020-05-03 21 10 04



Black - Focused
スクリーンショット 2020-05-01 22 31 40
Black -  Non focusing
スクリーンショット 2020-05-03 21 11 14

**Comment by kazuma0129** [comment]
Incidentally, the case of the same color is as follows.

スクリーンショット 2020-05-03 21 38 45
スクリーンショット 2020-05-03 21 38 54

**Comment by stefanalund** [comment]
@katz95 I think we may need to have a defined background for this icon.

**Comment by katz95** [comment]
hmm is it possible to have different color variations of a favicon depending on what color the tab is?

**Comment by kazuma0129** [comment]
It seems that you can set multiple sizes of favicon, but it seems not realistic to switch favicon dynamically according to the theme of the browser.

I think It is realistic to fix the background to white etc.

**Comment by katz95** [comment]
Good points! I've added a black background to the logo (#121212). Here are the favicons! 😊 Thanks for your help so far @kazuma0129 

[favicon_package_v0.16.zip](https://github.com/spotify/backstage-microsite/files/4579482/favicon_package_v0.16.zip)

**Comment by Rugvip** [comment]
@katz95 You can do it based on light/dark theme, but I don't think you can do it based on tab color

**Comment by kazuma0129** [comment]
I tried to verify it in this repository by referring to the following article.
- [Detect if the browser is using dark mode and use a different favicon
](https://stackoverflow.com/questions/55170708/detect-if-the-browser-is-using-dark-mode-and-use-a-different-favicon)

Below is a demo.
Since there was no favicon in SVG format, I used a temporary SVG format icon.
You'll notice that the favicon has changed to match the light/dark changes on the MAC.
[Image from Gyazo](https://gyazo.com/92c16d586f4fd6fa32dd80fdd4fa6d52)

As a result, as @Rugvip said, I was able to confirm that the light/dark theme can change the state of the favicon.

The specific method is.
- Prepare `img/favicon.svg`.
- Prepare the `style` tag.
- Detects light/dark with `@media (prefers-color-scheme: dark)` and dynamically changes the style of an element.
- Changed `favicon: "img/favicon.ico"` in `website/siteConfig.js` to `favicon: "img/favicon.svg"`.
- yarn build

You can reproduce it with the above.

**Comment by stefanalund** [comment]
That’s awesome! @katz95 can you provide SVG versions?

**Comment by katz95** [comment]
wow! amazing! thank you @kazuma0129. Here are the SVGs. The teal one should be used when the tab is dark. The black one should be used when the tab is light. Thank you!!!!!!!
[LogoSVGs.zip](https://github.com/spotify/backstage-microsite/files/4598502/LogoSVGs.zip)

**Comment by kazuma0129** [comment]
Thank you too @katz95 !!
I was able to confirm the operation with the SVG icon you uploaded.

#7df3e1 if your browser's theme is dark
When it's light, it's #121212.
I've pushed out a new change commit, so please check it out.

Here's a demo
[Image from Gyazo](https://gyazo.com/cfce53a718b17645ca95fdee7966cb6b)

**Comment by katz95** [comment]
@kazuma0129 AMAZING! you rock! thank you!!!!!

**Pull request merged**
