### PR TITLE
Background color change for The Spotify Story section

### LINKED ISSUE #120: Background color change for "The Spotify Story" section
The top of this section should be the same background color as the background color behind the quotation. There shouldn't be stark contrast.

**Currently**
76857038-e95dc680-6854-11ea-903d-03d47b868652

**Ideally**
76857241-52ddd500-6855-11ea-8c15-53b5678a931b

### PR DESCRIPTION
**Pull request by mateusmarquezini**
## Hey, I just made a Pull Request!

Fixes #120

- Changed background color for the Spotify Story section according to these specs: #120 

spotify_story_background

#### :heavy_check_mark: Checklist

- [x] Website is working locally `yarn start`
- [x] Screenshots attached (for UI changes)
- [x] Prettier run on changed files

### CODE REVIEW

**Comment by katz95** [comment]
@mateusmarquezini could we make the color #121212 rather than #000000? thank you so much!

**Comment by katz95** [comment]
referring to the background color behind this text 🥳Screenshot 2020-04-01 at 9 43 02 AM

**Comment by mateusmarquezini** [comment]
> @mateusmarquezini could we make the color #121212 rather than #000000? thank you so much!

Sure! Let me know what you think now @katz95. I've updated the screenshot in the description too! :smiley:

**Comment by stefanalund** [comment]
@katz95 feel free to merge if you are happy :)

**Comment by katz95** [comment]
Thank you so much @mateusmarquezini!!!!!!!

**Pull request merged**
